version: '3.7'

services:
  my_pypi:
    build: ./app
    command: gunicorn --bind 0.0.0.0:8000 --chdir my_pypi/ app:gunicorn_app
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=my_pypi
      - POSTGRES_PASSWORD=my_pypi
      - POSTGRES_DB=my_pypi_dev
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - my_pypi
volumes:
  postgres_data: